### ISSUE TITLE
Is this suitable for production?

### ISSUE THREAD

**Issue by callumacrae** [floatdrop/gulp-plumber#28]
Hey! The current version of this module is 0.6.6. Is it stable? If so, could you release 1.0.0?

**Comment by floatdrop** [comment]
@callumacrae I don't quite understand, what you mean under *production*, but API certainly will not change, so `1.0.0` it is.

**Note**: there are some compatibility issues with other plugins, check issues for list of them.

**Comment by callumacrae** [comment]
cheers
