### ISSUE TITLE
Plumber busts task out of `gulp.watch`

### ISSUE THREAD

**Issue by tomekwi** [floatdrop/gulp-plumber#29]
When using [`gulp.watch`](https://github.com/gulpjs/gulp/blob/master/docs/API.md#gulpwatchglob-opts-tasks), here’s what happens:

```sh
$ gulp watch
[11:36:53] Starting 'scripts'...
[11:36:53] Finished 'scripts' after 197 ms
[11:36:53] Starting 'styles'...
[11:36:53] Plumber found unhandled error:
 Error in plugin 'gulp-less'
Message:
    Unrecognised input. Possibly missing something in ...
Details:
    ...
# Changed some files
[11:37:15] Starting 'scripts'...
[11:37:15] Finished 'scripts' after 179 ms
# Changed some files again
[11:39:10] Starting 'scripts'...
[11:39:10] Finished 'scripts' after 179 ms
```

After an error has been caught in `scripts`, the task is never resumed. Is this the intended behavior?

**Comment by floatdrop** [comment]
Hard to say with out `gulpfile` to reproduce.

**Comment by floatdrop** [comment]
`gulp.watch` issues belongs here - https://github.com/gulpjs/gulp/issues

**Comment by tomekwi** [comment]
I thought it’s a problem with the way `plumber` handles these errors.

Anyway, thanks for the link – cheers!

**Comment by floatdrop** [comment]
@tomekwi oops, sorry, I thought that issue were in `gulp-watch` repo. Could you provide `gulpfile` to figure this out?

**Comment by tomekwi** [comment]
@floatdrop I followed your suggestion and tried to replace `gulp.watch` with [`gulp-watch`](http://npm.im/gulp-watch) – regarded as more robust. But the issue remains.

Our gulpfile is quite complex, but I remembering encountering the same with simple builds. I’ll try to reproduce the thing with a simpler build and post it here – I’ll be right back!

**Comment by tomekwi** [comment]
Hey, I’ve tried to reproduce the error, even written a more complex gulpfile for that: https://gist.github.com/tomekwi/0d1818c89b6453917a6c . But it doesn’t look bad after all.

My original project definitely has the issue, and it has been there for a long time already. But it looks like it lies somewhere else.

Sorry for the false alarm.

**Comment by joepie91** [comment]
This should probably be reopened; specifically, it seems the issue is caused by [this](http://blog.ibangspacebar.com/handling-errors-with-gulp-watch-and-gulp-plumber/). A change to the default error handler should fix this, I think.

**Comment by garygreen** [comment]
@floatdrop I'm having the same problem. The article linked by @joepie91 fixed it -- could this be added to gulp plumber?
