### ISSUE TITLE
NPM : Tell the package author to fix their package.json file.

### ISSUE THREAD

**Issue by halilemreozen** [floatdrop/gulp-plumber#43]
When I try the install gulp-plumber this errors shown by npm

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '--save-dev',
1 verbose cli   'gulp-plumber' ]
2 info using npm@2.7.4
3 info using node@v4.2.2
4 verbose stack Error: Failed to parse json
4 verbose stack Trailing comma in object at 37:3
4 verbose stack   }
4 verbose stack   ^
4 verbose stack     at parseError (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:406:25)
4 verbose stack     at parseJson (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:86:51)
4 verbose stack     at C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:60:33
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (evalmachine.<anonymous>:380:3)
5 verbose cwd C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\external\Green-Time\dev
6 error Windows_NT 10.0.10240
7 error argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save-dev" "gulp-plumber"
8 error node v4.2.2
9 error npm  v2.7.4
10 error file C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\external\Green-Time\dev\package.json
11 error code EJSONPARSE
12 error Failed to parse json
12 error Trailing comma in object at 37:3
12 error   }
12 error   ^
13 error File: C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\external\Green-Time\dev\package.json
14 error Failed to parse package.json data.
14 error package.json must be actual JSON, not just JavaScript.
14 error
14 error This is not a bug in npm.
14 error Tell the package author to fix their package.json file. JSON.parse
15 verbose exit [ 1, true ]

**Comment by floatdrop** [comment]
```
10 error file C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\external\Green-Time\dev\package.json
11 error code EJSONPARSE
12 error Failed to parse json
12 error Trailing comma in object at 37:3
12 error }
12 error ^
```
