### ISSUE TITLE
Changes stream behavior

### ISSUE THREAD

**Issue by iliakan** [floatdrop/gulp-plumber#46]
Observe this:
```
var vfs = require('vinyl-fs');
var plumber = require('gulp-plumber');

var stream = vfs.src(__filename)
  .pipe(plumber())
  .pipe(vfs.dest('/tmp'))
  .on('data', function() {
    console.log("Never happens")
  });
```

The `on('data')` on the last stream never happens. But it should.

**Comment by iliakan** [comment]
Update: that's a kind of stream issue. If I remove `once('readable')` from gulp-plumber, all is fine.
With it the last stream somewhy has `isPaused() == true`.

**Comment by iliakan** [comment]
Tracked the problem down to https://github.com/nodejs/node/issues/1041.

The problem is in `unpipe` of the sink stream that happens because of assigning `once('readable')` handler by plumber.
It stops the flow.

**Comment by floatdrop** [comment]
Hi! Thanks for investigation, I'm honestly do not remeber, why `readable` is used in this place. It will be removed in next version.

**Comment by iliakan** [comment]
@floatdrop I found it out in issues: you needed it because streams were removing the error handler. Maybe remove it now if not needed? :)

**Comment by floatdrop** [comment]
@iliakan removed in `1.1.0` – tests are still green, so there should be no problems now.
