### ISSUE TITLE
Does not handle gulp.src errors?

### ISSUE THREAD

**Issue by iDVB** [floatdrop/gulp-plumber#49]
Running this code simply results in a standard gulp error...

``` javascript
gulp.src('./config1.json')
    .pipe($.plumber(function() {
      console.log('There was an issue');
      this.emit('end');
    }));
```

... `Error: File not found with singular glob`

Not sure if I'm using correctly, but I had figured that plumber would pick this up as well.

**Comment by floatdrop** [comment]
gulp-plumber attaches error handler to all underlying streams, so gulp-src still should be handled manually (or some streams concatenation magic should be applied).
