### ISSUE TITLE
Gulp plumber now 404 on NPM

### ISSUE THREAD

**Issue by harryrobbins** [floatdrop/gulp-plumber#55]
Gulp plumber was working a few hours ago on NPM (https://www.npmjs.com/package/gulp-plumber) but is now a 404 and won't install via NPM.

**Comment by briantschu** [comment]
@harryrobbins It seems to be loading for me now. Any luck for you?

**Comment by harryrobbins** [comment]
Yep - fixed. Thanks for the super-speedy response!

**Comment by briantschu** [comment]
Great! I didn't do anything to fix it, I was just experiencing the same issue :)

Looks like there's something going on with npmjs.org: https://status.npmjs.org/incidents/41zfb8qpvrdj
